/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import Model.Diskon;
import Model.Produk;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.List;

/**
 *
 * @author Advan
 */
public class PanelKasir extends javax.swing.JPanel {

    /**
     * Creates new form PanelKasir
     */
    public PanelKasir() {
        initComponents();
        loadProduk();
        loadDiskonHariIni();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        txtQty = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        lblDiskon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNoHP = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelProduk);
        if (tabelProduk.getColumnModel().getColumnCount() > 0) {
            tabelProduk.getColumnModel().getColumn(0).setResizable(false);
            tabelProduk.getColumnModel().getColumn(1).setResizable(false);
            tabelProduk.getColumnModel().getColumn(2).setResizable(false);
            tabelProduk.getColumnModel().getColumn(3).setResizable(false);
        }

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Harga", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelKeranjang);
        if (tabelKeranjang.getColumnModel().getColumnCount() > 0) {
            tabelKeranjang.getColumnModel().getColumn(0).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(1).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(2).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(3).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(4).setResizable(false);
        }

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        lblTotal.setText("Total: ");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        lblDiskon.setText("Diskon: ");

        jLabel1.setText("QTY :");

        lblNama.setText("Nama Pelanggan: ");

        lblNoHP.setText("No hp:");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama)
                                    .addComponent(lblNoHP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoHp)
                                    .addComponent(txtNama))))
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBayar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNoHP)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void loadDiskonHariIni() {
    dao.DiskonDao diskonDao = new dao.DiskonDao();
    Diskon diskon = diskonDao.getDiskonHariIni();

    double totalPersen = diskon.getPersen1() + diskon.getPersen2();

    if (totalPersen <= 0) {
        lblDiskon.setText("Tidak Ada Diskon Hari Ini");
    } else {
        lblDiskon.setText("Diskon Hari Ini: " + totalPersen + "%");
    }
}

    
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int row = tabelProduk.getSelectedRow();
        
        if (row == -1){
            JOptionPane.showMessageDialog(this, "Pilih Produk!");
            return;
        }
        
        int id = (int) tabelProduk.getValueAt(row, 0);
        String nama = (String) tabelProduk.getValueAt(row, 1);
        Double harga = (Double) tabelProduk.getValueAt(row, 2);
        int qty = 1;
        
        try{
            qty = Integer.parseInt(txtQty.getText());
            
            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah Harus Lebih Dari 0!!");
                return;
            }
            
            DefaultTableModel modelKeranjang = (DefaultTableModel) tabelKeranjang.getModel();

        // Tambahkan baris baru ke model yang sudah ada
        modelKeranjang.addRow(new Object[]{id, nama, harga, qty, harga * qty});
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukan Jumlah Yang benar!!!");
        }
        

        
        hitungTotal();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        try (Connection conn = Database.DatabaseConnection.GetConnection()) {
        conn.setAutoCommit(false);

        double total = 0;
        DefaultTableModel modelKeranjang = (DefaultTableModel) tabelKeranjang.getModel();
        for (int i = 0; i < modelKeranjang.getRowCount(); i++) {
            total += (double) modelKeranjang.getValueAt(i, 4);
        }

        // === CEK DISKON ===
        dao.DiskonDao diskonDao = new dao.DiskonDao();
        
        Diskon diskon = diskonDao.getDiskonHariIni();
        double pot1 = total * (diskon.getPersen1() / 100); // Diskon dari persen1
        double pot2 = total * (diskon.getPersen2() / 100); // Diskon dari persen2
        double totalDiskon = pot1 + pot2;
        double totalSetelahDiskon = total - totalDiskon;

        
        String sqlPelanggan = "INSERT INTO pelanggan (nama, no_hp) VALUES (?, ?)";
        PreparedStatement stmtPelanggan = conn.prepareStatement(sqlPelanggan, Statement.RETURN_GENERATED_KEYS);
        stmtPelanggan.setString(1, txtNama.getText());
        stmtPelanggan.setString(2, txtNoHp.getText());
        stmtPelanggan.executeUpdate();

        // Ambil id_pelanggan yang baru saja dibuat
        ResultSet rs = stmtPelanggan.getGeneratedKeys();
        rs.next();
        int idPelanggan = rs.getInt(1);

        // === SIMPAN KE TRANSAKSI ===
        String sqlTransaksi = "INSERT INTO transaksi (id_pelanggan, tanggal, total, diskon, total_real) VALUES (?, NOW(), ?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sqlTransaksi, Statement.RETURN_GENERATED_KEYS);
        stmt.setInt(1, idPelanggan);
        stmt.setDouble(2, total);
        stmt.setDouble(3, totalDiskon);
        stmt.setDouble(4, totalSetelahDiskon);
        stmt.executeUpdate();

        ResultSet rst = stmt.getGeneratedKeys();
        rst.next();
        int idTransaksi = rst.getInt(1);

        // === SIMPAN DETAIL TRANSAKSI ===
        String sqlDetail = "INSERT INTO detail_transaksi (id_transaksi, id_produk, qty, subtotal) VALUES (?, ?, ?, ?)";
        PreparedStatement stmtDetail = conn.prepareStatement(sqlDetail);

        for (int i = 0; i < modelKeranjang.getRowCount(); i++) {
            stmtDetail.setInt(1, idTransaksi);
            stmtDetail.setInt(2, (int) modelKeranjang.getValueAt(i, 0));
            stmtDetail.setInt(3, (int) modelKeranjang.getValueAt(i, 3));
            stmtDetail.setDouble(4, (double) modelKeranjang.getValueAt(i, 4));
            stmtDetail.addBatch();
        }

        stmtDetail.executeBatch();
        conn.commit();

        JOptionPane.showMessageDialog(this,
            "Transaksi berhasil!\n" +
            "Diskon: " + pot1 + "%" + pot2 + "%" +"\n" +
            "Total Bayar: Rp " + totalSetelahDiskon);

        modelKeranjang.setRowCount(0);
        lblTotal.setText("Total: Rp 0");

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed
    
    private void loadTotal(){
        double total = 0;
        DefaultTableModel modelKeranjang = (DefaultTableModel) tabelKeranjang.getModel();
        for (int i = 0; i < modelKeranjang.getRowCount(); i++) {
            total += (double) modelKeranjang.getValueAt(i, 4);
        }
    }
    
    private void hitungTotal(){
        double total = 0;
        DefaultTableModel model = (DefaultTableModel) tabelKeranjang.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            total += (double) model.getValueAt(i, 4);
        }
        lblTotal.setText("Total: Rp " + total);
    }
    
    private void loadProduk() {
    dao.ProductDao dao = new dao.ProductDao();
    List<Produk> list = dao.tampilkanSemuaProduk();


    // Buat model tabel
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new Object[]{"ID", "Nama", "Harga", "Stok"}, 0
    );

    // Isi data produk
    for (Model.Produk p : list) {
        model.addRow(new Object[]{
            p.getId(),
            p.getNama(),
            p.getHarga(),
            p.getStok()
        });
    }

    tabelProduk.setModel(model);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoHP;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
