/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import dao.ProductDao;
import Model.Produk;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Advan
 */
public class PanelProduk extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduk
     */
    public PanelProduk() {
        initComponents();
        loadProduk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        txtProduk = new javax.swing.JTextField();
        txtHargaProduk = new javax.swing.JTextField();
        txtStokProduk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelProduk);

        txtStokProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokProdukActionPerformed(evt);
            }
        });

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Produk");

        jLabel2.setText("Harga Produk");

        jLabel3.setText("Stok Produk");

        jLabel4.setText("Menambah Produk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStokProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtProduk)
                            .addComponent(txtHargaProduk))
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStokProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadProduk(){
        ProductDao dao = new ProductDao();
        List<Produk> list = dao.tampilkanSemuaProduk();
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Nama", "Harga", "Stok"},0
        );
        for (Produk p : list){
            model.addRow(new Object[]{p.getId(), p.getNama(), p.getHarga(), p.getStok()});
        }
        tabelProduk.setModel(model);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusProduk();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void hapusProduk() {
    int row = tabelProduk.getSelectedRow();
    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih produk yang ingin dihapus!");
        return;
    }

    int id = (int) tabelProduk.getValueAt(row, 0);
    int confirm = JOptionPane.showConfirmDialog(this, 
                "Yakin ingin menghapus produk ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if(confirm != JOptionPane.YES_OPTION) return;

    ProductDao dao = new ProductDao();
    dao.deleteProduk(id);

    loadProduk(); // refresh tabel
    JOptionPane.showMessageDialog(this, "Produk berhasil dihapus!");
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        // Ambil input user
        String nama = txtProduk.getText();
        Double harga = Double.parseDouble(txtHargaProduk.getText());
        int stok = Integer.parseInt(txtStokProduk.getText());

        if (nama.isEmpty() || harga <= 0 || stok < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Pastikan nama, harga (>0) dan stok (>=0) valid!");
            return;
        }

        // Buat objek Produk
        Produk p = new Produk(nama, harga, stok);

        // Insert ke database
        ProductDao dao = new ProductDao();
        dao.insertProduk(p);

        // Tampilkan pesan sukses
        javax.swing.JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan!");

        // Bersihkan field input
        txtProduk.setText("");
        txtHargaProduk.setText("");
        txtStokProduk.setText("");

        // Refresh tabel
        loadProduk();

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Harga dan Stok harus angka!");
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Gagal menambahkan produk: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStokProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokProdukActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ubahProduk();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ubahProduk() {
    int row = tabelProduk.getSelectedRow();
    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih produk yang ingin diubah!");
        return;
    }

    int id = (int) tabelProduk.getValueAt(row, 0);
    String namaLama = (String) tabelProduk.getValueAt(row, 1);
    Double hargaLama = (Double) tabelProduk.getValueAt(row, 2);
    int stokLama = (int) tabelProduk.getValueAt(row, 3);

    String namaBaru = JOptionPane.showInputDialog(this, "Nama Produk:", namaLama);
    if(namaBaru == null) return; // batal
    String hargaStr = JOptionPane.showInputDialog(this, "Harga Produk:", hargaLama);
    if(hargaStr == null) return;
    String stokStr = JOptionPane.showInputDialog(this, "Stok Produk:", stokLama);
    if(stokStr == null) return;

    double hargaBaru = Double.parseDouble(hargaStr);
    int stokBaru = Integer.parseInt(stokStr);

    Produk p = new Produk(id, namaBaru, hargaBaru, stokBaru);
    ProductDao dao = new ProductDao();
    dao.updateProduk(p);

    loadProduk(); // refresh tabel
    JOptionPane.showMessageDialog(this, "Produk berhasil diperbarui!");
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTextField txtHargaProduk;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtStokProduk;
    // End of variables declaration//GEN-END:variables
}
