/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Diskon;
import dao.DiskonDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Advan
 */
public class PanelDiskon extends javax.swing.JPanel {

    /**
     * Creates new form PanelDiskon
     */
    public PanelDiskon() {
        initComponents();
        jLabel2.setText("Tanggal (YYYY-MM-DD):");
        jLabel3.setText("Diskon 1 (%):");
        jLabel4.setText("Diskon 2 (%):");

        // pastikan tabel awal model sesuai
        tabelDiskon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Tanggal", "Diskon 1", "Diskon 2"}
        ) {
            boolean[] canEdit = new boolean [] {false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) { return canEdit [columnIndex]; }
        });

        loadDiskon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDiskon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtDiskon1 = new javax.swing.JTextField();
        txtDiskon2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        tabelDiskon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelDiskon);
        if (tabelDiskon.getColumnModel().getColumnCount() > 0) {
            tabelDiskon.getColumnModel().getColumn(0).setResizable(false);
            tabelDiskon.getColumnModel().getColumn(1).setResizable(false);
            tabelDiskon.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setText("Tanggal :");

        jLabel3.setText("diskon 1 :");

        jLabel4.setText("diskon 2 :");

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jButton1.setText("tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDiskon1)))
                                .addGap(40, 40, 40)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiskon2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiskon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiskon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
        String tanggalStr = txtTanggal.getText().trim();
        double persen1 = Double.parseDouble(txtDiskon1.getText());
        double persen2 = Double.parseDouble(txtDiskon2.getText());

        if (tanggalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong!");
            return;
        }

        // 🔸 ubah String ke java.sql.Date (format: yyyy-MM-dd)
        java.sql.Date tanggal = java.sql.Date.valueOf(tanggalStr);

        Diskon d = new Diskon(tanggal, persen1, persen2);
        new DiskonDao().insertDiskon(d);

        JOptionPane.showMessageDialog(this, "Diskon berhasil ditambahkan!");
        loadDiskon();

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal harus yyyy-MM-dd!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menambah diskon: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = tabelDiskon.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data diskon yang ingin diubah!");
        return;
    }

    // Ambil data dari tabel
    int id = (int) tabelDiskon.getValueAt(row, 0);
    String tglLama = tabelDiskon.getValueAt(row, 1).toString();
    double persen1Lama = Double.parseDouble(tabelDiskon.getValueAt(row, 2).toString());
    double persen2Lama = Double.parseDouble(tabelDiskon.getValueAt(row, 3).toString());

    // Input baru dari user
    String tglBaruStr = JOptionPane.showInputDialog(this, "Tanggal (yyyy-MM-dd):", tglLama);
    if (tglBaruStr == null || tglBaruStr.trim().isEmpty()) return;

    String persen1Str = JOptionPane.showInputDialog(this, "Diskon 1 (%):", persen1Lama);
    if (persen1Str == null || persen1Str.trim().isEmpty()) return;

    String persen2Str = JOptionPane.showInputDialog(this, "Diskon 2 (%):", persen2Lama);
    if (persen2Str == null || persen2Str.trim().isEmpty()) return;

    try {
        java.sql.Date tanggal = java.sql.Date.valueOf(tglBaruStr.trim());
        double persen1 = Double.parseDouble(persen1Str);
        double persen2 = Double.parseDouble(persen2Str);

        Diskon d = new Diskon(tanggal, persen1, persen2);
        d.setId(id);

        DiskonDao dao = new DiskonDao();
        dao.updateDiskon(d);

        JOptionPane.showMessageDialog(this, "Diskon berhasil diperbarui!");
        loadDiskon(); // refresh tabel
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal harus yyyy-MM-dd!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal ubah diskon: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = tabelDiskon.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data diskon yang ingin dihapus!");
        return;
    }

    int id = (int) tabelDiskon.getValueAt(row, 0);
    int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus data diskon ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            DiskonDao dao = new DiskonDao();
            dao.deleteDiskon(id);
            JOptionPane.showMessageDialog(this, "Diskon berhasil dihapus!");
            loadDiskon(); // refresh tabel
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus diskon: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setupTabelDiskon() {
    // atur model tabel di luar initComponents
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID", "Tanggal", "Diskon 1", "Diskon 2"}, 0
    );
    tabelDiskon.setModel(model);
    }
    
    private void loadDiskon() {
    DiskonDao dao = new DiskonDao();
    List<Diskon> list = dao.getSemuaDiskon();

    DefaultTableModel model = (DefaultTableModel) tabelDiskon.getModel();
    model.setRowCount(0); // hapus data lama

    for (Diskon d : list) {
        model.addRow(new Object[]{
            d.getId(),
            d.getTanggal(),
            d.getPersen1(),
            d.getPersen2()
        });
    }
    }


        
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDiskon;
    private javax.swing.JTextField txtDiskon1;
    private javax.swing.JTextField txtDiskon2;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
